# -*- coding: utf-8 -*-
"""Data_Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZMvkgoULlv50zh1X_oYnzhK8GHKFCo4
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.relplot(x ="Goals_Conceded", y = "Goals_Saves",hue = "Name",data = df1);
plt.title("Number of Goals Saved vs. Number of Goals Conceded")
plt.xlabel("Number of Goals Conceded")
plt.ylabel("Number of Goals Saved")
plt.show()

plt.figure(figsize=(30, 10))
sns.barplot(data=df1, x='Team', y='Goals_Total', hue='Position')
plt.title('Goals by each team with respect to position')
plt.show()

sns.pairplot(data=df1, vars=['Dribbles_Attempts', 'Dribbles_Success', 'Goals_Total', 'Rating'])
plt.title('Pairplot of Dribbles_Attempts, Dribbles_Success, Goals_Total, Rating')
plt.show()

plt.figure(figsize=(30, 10))
sns.violinplot(data=df1, x='Team', y='Accuracy_Passes', hue='Position')
plt.title('Accurary passes of players in each team based on the position')
plt.show()

plt.figure(figsize=(30, 10))
sns.pointplot(data=df1, x='Team', y='Rating', hue='Position')
plt.title('Average Rating of players of each team based on their position')
plt.show()

plt.figure(figsize=(20, 8))
sns.heatmap(data=df1.corr(), annot=True)
plt.title('Heatmap')
plt.show()

plt.figure(figsize=(10,5))
sns.displot(x='Height_cm', y='Fouls_Committed', data=df1)
plt.title('Height vs Fouls Committed')
plt.show()

labels = df1['Yellow_Red_Cards'].value_counts().index
sizes = df1['Yellow_Red_Cards'].value_counts().values
fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(aspect="equal"))
wedges, texts, autotexts = ax.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90)
ax.legend(wedges, labels, title="Yellow and Red Cards", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1))
plt.setp(autotexts, size=8, weight="bold")
ax.set_title("Distribution of Players based on the Number of Yellow and Red Cards")
plt.show()

plt.figure(figsize=(45,10))
sns.countplot(x='Nationality', data=df1)
plt.title('Countplot of Nationality')
plt.show()

plt.figure(figsize=(10,8))
sns.pointplot(x='Position', y='Minutes', data=df1)
plt.title('Minutes Played vs Position')
plt.show()