# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QeHKe3zyUj09B7PDBL8qResGb4-vuxZY
"""

import pandas as pd
df1 = pd.read_csv('/content/df_championship_140_2023-02-0508_34_07 (1).csv')

duplicateRows = df1[df1.duplicated()]
duplicateRows

df1= df1.drop_duplicates()

df1.drop(['Photo','Logo_Team'], inplace=True, axis=1)
df1.drop(['Dribbles_Past','Tackled_Total','Tackled_Block'], inplace=True, axis=1)

df1['Injured'].value_counts()

df1.drop(['Injured'],inplace=True,axis=1)

df1.dropna(subset=['Rating'],inplace=True)

df1['Weight_kg'].fillna(df1['Weight_kg'].median(),inplace=True)
df1['Height_cm'].fillna(df1['Height_cm'].median(),inplace=True)

df1['Goals_Assist'].fillna(0,inplace=True)